### ISSUE TITLE
Instagram has returned invalid data

### ISSUE THREAD

**Issue by ybhrc** [scottsweb/wp-instagram-widget#120] opened 2019-09-03 15:55 UTC
Hello- I have the message "Instagram has returned invalid data" displaying on my website. I am not a coder so if you have a simple fix that a simple mind can understand that would be great. I did try to deactivate and reactivate the plugin.

I have version 2.0.3

Thank you

**Comment by scottsweb** [comment] 2019-09-03 15:57
Duplicate of https://github.com/scottsweb/wp-instagram-widget/issues/120

**Closed by scottsweb** 2019-09-03 15:57 UTC

**Comment by ybhrc** [comment] 2019-09-03 15:59
When I click on #120 it doesn't take me anywhere

**Comment by scottsweb** [comment] 2019-09-03 16:00
Apologies. Try: https://github.com/scottsweb/wp-instagram-widget/issues/118
