### ISSUE TITLE
Photo Sizes

### ISSUE THREAD

**Issue by m0hamm4dElmi** [scottsweb/wp-instagram-widget#33] opened 2015-12-04 17:14 UTC
Hey,
Attached image is var_dump of below code:
 $media_array = $this->scrape_instagram( $username, $limit );

Red border is color of first instagram image of "smartblog1", as you can see ["thumbnail"], ["small"], ["large"], ["original"]  are not functioning correctly and they are returning original image.
Blue border is second image which is returning all image sizes correctly.
Do you have any idea for this issue?

https://www.dropbox.com/s/cylcffrr1e8gnf6/wp-instagram-widget.jpg?dl=0

related instagram url: https://www.instagram.com/smartblog1/ 

At the end, thanks so much for your awesome plugin :)

**Comment by scottsweb** [comment] 2015-12-04 17:26
This is a duplicate of #29 and has been reported in #32 as well. 

Instagram have changed the CDN urls for images recently and the sizing code has broken as a result. I will close this ticket and track it in the other two. 

I was hoping that it would be fixed in #32 by someone else. No such luck.

**Closed by scottsweb** 2015-12-04 17:26 UTC

**Comment by m0hamm4dElmi** [comment] 2015-12-05 07:02
OK, Thanks.
I'd like to know if there a way to change codes to get only thumbnails in 320px as output?

**Comment by scottsweb** [comment] 2015-12-06 13:11
I haven't really tested this yet but there are details of how image sizes are working here: https://wordpress.org/support/topic/some-images-use-thumbnails-other-use-larger-versions?replies=5#post-7590707

**Comment by scottsweb** [comment] 2015-12-09 15:08
This is now fixed

**Comment by m0hamm4dElmi** [comment] 2015-12-11 10:01
Thank you very much!
